name: Bug Report
description: Report a bug in SimpleVecDB
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Minimal code to reproduce the issue.
      placeholder: |
        ```python
        from simplevecdb import VectorDB
        db = VectorDB(":memory:")
        # ... code that triggers bug
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include error messages if applicable.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: SimpleVecDB version
      placeholder: "2.0.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.11"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context about the problem (logs, screenshots, etc.)
    validations:
      required: false
